app:
  image: tutum/hello-world:latest
  environment:
    SERVICE_80_NAME: http
    SERVICE_NAME: app
    SERVICE_TAGS: production
  ports:
    - 80

lb:
  image: 1science/nginx:1.9.0
  links:
    - consul
  ports:
    - 80:80
  volumes:
    - config:/etc/consul-templates

consul:
  command: -server -bootstrap -ui-dir /ui -advertise 10.0.2.15
  image: progrium/consul:latest
  ports:
    - 8300:8300
    - 8400:8400
    - 8500:8500
    - 8600:53/udp

registrator:
  command: consul://consul:8500
  image: progrium/registrator:latest
  links:
    - consul
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock