# Sample application
app:
  image: tutum/hello-world:latest
  environment:
    # Environment variables used by registrator to register services in consul
    SERVICE_NAME: app
    SERVICE_TAGS: sample
  ports:
    - 81:80

# Nginx Load Balancer
lb:
  build: .
  links:
    - consul
  ports:
    - 80:80
  volumes:
    - ./templates:/etc/consul-templates

# Consul & registrator for service discovery
consul:
  command: -ui-dir=/ui -bootstrap-expect 1
  image: gliderlabs/consul-server:0.5
  ports:
    - 8300:8300
    - 8400:8400
    - 8500:8500
    - 8600:53/udp

registrator:
  command: consul://consul:8500
  image: gliderlabs/registrator:v6
  links:
    - consul
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock