# Sample application
app:
  image: tutum/hello-world:latest
  environment:
    # Environment variables used by registrator to register services in consul
    SERVICE_NAME: app
    SERVICE_TAGS: sample
  ports:
    - 80

# Nginx Load Balancer
lb:
  image: 1science/nginx:1.9.0
  links:
    - consul
  ports:
    - 80:80
  volumes:
    - config:/etc/consul-templates
  environment:
    NGINX_CONF: /etc/nginx/nginx-sites.conf

# Consul & registrator for service discovery
consul:
  command: -server -bootstrap -ui-dir /ui -advertise 10.0.2.15
  image: progrium/consul:latest
  ports:
    - 8300:8300
    - 8400:8400
    - 8500:8500
    - 8600:53/udp

registrator:
  command: consul://consul:8500
  image: progrium/registrator:latest
  links:
    - consul
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock